---
title: "練習1"
date: "2018-10-03"
output: html_document
params:
  studentID: ""
  studentName: "答案"
---

## 1
安裝套件及引入資料
```{r}
#install.packages(readr); install.packages(dplyr); install.packages(stringr); install.packages(lubridate)
library(readr); library(dplyr); library(stringr); library(lubridate)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/midterm-data/classSurvey.csv")
hwGrades <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/midterm-data/hwGrades.csv")
hwSubmit <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/midterm-data/hwSubmit.csv")
```

## 2
將classSurvey資料中的**性別**變數轉成factor class
```{r ans11}
as.factor(classSurvey$`性別`) -> classSurvey$`性別`
```

## 3
將年月改成西元年月
```{r ans12}
library(lubridate)
library(stringr)
str_c("1",bankdata$年月,"/01") -> dateTime
ymd(dateTime)+years(911) -> dateTime
bankdata$年月 <- dateTime
```

## 2
Google天災地圖會發佈天災時地資訊，如[潭美颱風(Typhoon Trami)](https://google.org/crisismap/google.com/2018-trami)，但它的時間是以UTC表示，如"2018/30/09 00:00 UTC",試透過`lubridate::with_tz()`將"2018/30/09 00:00 UTC"轉成台灣時間。(Hint: 台灣tzone可用`grep("Taipei",OlsonNames(),value=TRUE)`指令查得)

```{r ans2}
library(lubridate)
with_tz(ymd_hm("2018/09/30 00:00"), tzone="Asia/Taipei")
```


